linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - typecheck
      - fieldalignment
      - shadow

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - goconst
    - gocritic
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - varcheck

